### ISSUE TITLE
Visual Prototype - Single Page Design with Nature Theme

### ISSUE THREAD

**Issue by kimeisele** [kimeisele/tempelbegleiter#3]
## Visual Prototype Specification (2025-06-08 23:16:14 UTC)
Author: @kimeisele

#### 1. Color Scheme
```css
:root {
  --saffron: #FF7F00;     /* Primary - Headers, highlights */
  --sage: #58B19F;        /* Secondary - Accents, borders */
  --gold: #FFD700;        /* Accent - Special elements */
  --text: #333333;        /* Main text */
  --bg-light: #FFF9F2;    /* Background light */
  --bg-dark: #FCF3E8;     /* Background darker sections */
}
```

#### 2. Typography
```css
/* Clean, readable typography */
body {
  font-family: 'Source Sans Pro', sans-serif;
  line-height: 1.6;
}

.verse-text {
  font-family: 'Noto Sans', sans-serif; /* For diacritical marks */
  font-size: 1.2em;
  letter-spacing: 0.02em;
}
```

#### 3. Layout Structure
```html
<div class="container">
  <!-- Header with peaceful mountain background -->
  <header class="main-header">
    <h1>Tempelbegleiter</h1>
    <div class="search-bar">
      <!-- Quick verse lookup -->
    </div>
  </header>

  <!-- Main content area -->
  <main class="content">
    <!-- Verse display -->
    <section class="verse-display">
      <div class="verse-header">
        <h2>Bhagavad-gītā 12.32</h2>
        <div class="verse-tags">
          <!-- Tag system implementation -->
        </div>
      </div>
      
      <div class="verse-content">
        <p class="verse-text">
          Hare Kṛṣṇa Hare Kṛṣṇa
          Kṛṣṇa Kṛṣṇa Hare Hare
          Hare Rāma Hare Rāma
          Rāma Rāma Hare Hare
        </p>
        
        <p class="verse-translation">
          [German translation]
        </p>
      </div>
    </section>

    <!-- Related content -->
    <aside class="sidebar">
      <!-- Chapter navigation -->
      <!-- Related verses -->
      <!-- Quick links -->
    </aside>
  </main>
</div>
```

#### 4. Image Integration
```css
/* Nature-themed background images */
.header-bg {
  background-image: url('unsplash-mountains.jpg');
  /* Will use Unsplash API for:
     - Mountain landscapes
     - Peaceful nature scenes
     - Cows in nature
  */
}
```

#### 5. Responsive Design
```css
/* Mobile-first approach */
@media (min-width: 768px) {
  .content {
    display: grid;
    grid-template-columns: 3fr 1fr;
    gap: 2rem;
  }
}
```

### Interactive Features
1. Smooth transitions between verses - nice but robust implementation general light code 
2. Tag system with color-coded categories
3. Quick copy verse references
4. Dynamic background images

### Next Steps
Would you like me to:
1. Create a live HTML prototype with this design? yes
2. Add more specific color variations?lets keep it simple
3. Implement the tag system UI? yes 

### Example Usage
```
bg 12 32 -> Shows verse with:
- Clean layout
- Saffron highlights
- Nature background backgrond image ? but lets not overdo it keeping usability in center + performance
- Tag suggestions
```
